<style>
    .back
    {
        background-color: rgba(255,246,234,255);
        color:black;
    }
</style>

<img src = "spa.png">
<div class = "back">
<h1 class = "text-center titlefont-bold p-10 text-xl">A Customised Experience</h1>
<div class = "text-sm flex flex-col items-center content-regular">
<img src = "spa1.png" class = "w-80 ">
<p class = "">
    The Oberoi Spa offers a selection of Ancient Indian wellness treats and contemporary
spa treatments to restore a sense of calm and harmony . Therapists well-versed in
the art of imparting wellness, guide you through elevating experiences that result in
enlivening all five senses to a point beyond and experience that inner harmony and
relaxation.
</p>
<p>
    Choose from an array of Ancient Indian, Oriental and Western influenced treatments
to restore the vital energies of the body, or select from our range of beauty treatments
that impart nourishment and radiance.
</p>
<p>
    Whatever your preference, your time at The Oberoi Spa will leave you refreshed,
renewed and re-energised.
</p>
<p>
    All you need to decide is the time you wish to spend at our spa, and then allow our
team to deliver an experience that you will cherish forever.
</p>
<p>Pricing:</p>
<img src = "price1.png" width=200px>
</div>

<div class = "content-regular">
    <img src = "obr1.png">
    <p style="text-align: center;margin-bottom: 0cm;background: transparent;line-height: 115%;"><b>Oberoi Experiences</b><br>Our specially curated wellness and beauty spa rituals combine select treatments to rejuvenate and relax the body and<br>being. Each Oberoi Experience caters to your specific needs, delivers holistic care and transports you to a state of peace<br>and calm.<br>Rejuvenate<br>180 minutes Spa Experience<br>The journey begins with long, symmetrical massage strokes delivered with a warm poultice, prepared with Indian herbs<br>and warm therapeutic oil.<br>This is followed by a customized facial to suit your needs. The experience concludes with a classic head massage for the<br>scalp, neck and shoulders. This experience promotes a profound sense of oneness and wellbeing.<br>(Hot Poultice &bull; Facial &bull;Head massage)<br>Revitalise<br>150 minutes Spa Experience<br>This treatment pulls you into instant relaxation, starting with a calming back massage to ease muscular knots, aches and<br>tension. A nourishing customized facial treatment follows. Your therapist then delivers a hand massage to hydrate the<br>skin, giving it a burst of radiance. An intensive leg and foot massage is administered to relieve stress and restore balance.<br>(Back Massage &bull; Facial &bull; Hands &bull; Feet)<br>Relax<br>120 minutes Spa Experience<br>The experience commences with a gentle and thorough exfoliation of the body. A full body massage follows, with select<br>oils to nourish the skin and restore the body&rsquo;s natural balance. Choose either a Balinese or a Swedish massage to ease<br>deep-seated tensions and relax your body and mind.<br>(Body Exfoliation &bull; Full body massage)</p>
    <img src = "obr3.png">
    <p style="text-align: center;margin-bottom: 0cm;background: transparent;line-height: 115%;">Massage<br>From pain relief to deep relaxation, a skillfully delivered massage is excellent for your overall health and wellbeing.<br>The Oberoi Spa offers the most effective massage therapies that soothe the senses, restore vitality and revive the spirit.<br>Oberoi Signature &emsp;&emsp; 75 /90 minutes<br>Relax your mind, body and senses with our signature massage. Our Signature Massage with kasa bowls offers an<br>experience of &lsquo;Sense of Place&rsquo;. Rooted in Ancient Indian healing, use of &lsquo;kasa&rsquo; metal for its therapeutic effects on body<br>and mind has been mentioned in Ayurveda. Your therapist works into your muscles using rhythmic soothing strokes<br>coupled with deeper strokes using warm &lsquo;kasa bowls&rsquo;. This treatment is excellent for releasing muscular tension, increasing<br>circulation and relieving stiffness. Customised to suit your specific needs.<br>Swedish&emsp;&emsp;60/75/90 minutes<br>The most widely practiced and best known Western technique, Swedish massage is designed to invigorate and renew.<br>The healing hands of your therapist provide a classic combination of strokes and pressure techniques to improve micro-<br>circulation, release muscular tension and relieve aches and pains. The experience leaves you refreshed and rejuvenated.<br>Balinese &emsp;&emsp; 60/75/90 minutes<br>Developed on the island of Bali, this luxurious massage therapy combines the revitalising properties of aromatic oils with<br>deep pressure techniques such as skin rolling, deep tissue manipulation and reflexology. A sense of calm and well-being<br>envelops you as vital energy points are stimulated and muscle tension is eased.<br>Hot Stone&emsp;&emsp; 75/90 minutes<br>This massage uses a combination of heat and pressure to create long-lasting benefits. Smoothened volcanic stones,<br>suffused with the earth&rsquo;s energies, and natural oils, are heated to intensify the effects. As these glide over and knead your<br>body, you feel a sense of deep relaxation and balance descend upon you.<br>Dry Massage&emsp;&emsp; 60/75 minutes<br>Anticipating guests &apos;sensitivity to &lsquo;touch therapies&rsquo; during post pandemic period, this specially curated &lsquo;Dry massage&rsquo;<br>is designed to deliver an experience that involves minimal skin to skin contact. This treatment begins with a breathing<br>practice followed by a full body massage involving stretching, dry muscle manipulation and activation of certain vital<br>pressure points.</p>
    <img src = "obr2.png">
    <p style="text-align: center;margin-bottom: 0cm;background: transparent;line-height: 115%;">Body Treatments<br>Body Exfoliation&emsp;&emsp; 30 minutes<br>Exfoliation is a vital deep-cleansing technique whereby accumulated dead cells are gently scrubbed away to reveal fresh,<br>radiant skin. A selection of natural blends is used to nourish and buff the skin, improving cell regeneration and blood<br>circulation. The therapy is concluded with a hydrating application of body butter.<br>&bull; Himalayan rice scrub<br> &nbsp; &nbsp;An ancient Indian preparation; this blend replenishes moisture and restores the skin&rsquo;s natural sheen. Almond powder<br>and grains of Himalayan rice work together to gently remove dead skin cells, revealing a satin-smooth texture as your<br>body takes on a noticeably brighter tone.<br>&bull; Indian rose and salt scrub<br>&nbsp; &nbsp; This mineral-rich blend creates gentle abrasion and sloughs away pollutants, detoxifying the skin. The coarse texture<br>effectively refines the pores and draws out impurities to reveal a youthful freshness. You are left with plump and<br>glowing skin.<br>Body Envelopment&emsp;&emsp; 30 minutes<br>The treatment starts with a full body brushing to prepare the body for a wrap. The application of a masque follows, and<br>the body is cocooned in a warmth-inducing wrap to facilitate natural detoxification, firming and nourishment. Relax<br>with a dry head massage while the masque is working its way into the deeper layers of your skin.<br>&bull; Red Mud<br>&nbsp; &nbsp; An indigenous Indian herbal mixture, this cleansing masque envelopes you in a cocoon of heat and nourishment.<br>Heat-inducing herbs and spices such as ginger, rice and nutmeg are combined to relieve muscular stiffness, aches and<br>pains. The masque gently exfoliates the skin, fires up your body&rsquo;s systems and relaxes the nerves.<br>&bull; Indian Sandalwood<br>&nbsp; &nbsp; A centuries-old concoction from India, this masque draws out impurities and deeply conditions the skin. Your<br>therapist lathers your body with the smooth-textured salve, forming a snug sheath of nourishment. Your skin is<br>rejuvenated and bathed in the sweet, earthy aromas of sandalwood that cling to you enticingly for the rest of the day.</p>
    <img src = "obr4.png">
    <p style="text-align: center;margin-bottom: 0cm;background: transparent;line-height: 115%;">Energy Balancing Treatments<br>Our energy balancing treatments are especially designed to encourage guests embark on their wellness journey by<br>experiencing treatments inspired from Ancient Indian healing wisdom . Each treatment is designed to improve overall<br>wellbeing and vitality.<br>Himalayan Singing Bowls&emsp;&emsp; 90 minutes<br>This revitalising therapy begins by placing Himalayan singing bowls over specific energy points and creating sonic<br>vibrations that ripple through the body, relieving fatigue and calming the senses. The treatment continues with a<br>customized massage therapy delivered to activate energy centres .The experience draws you into a deeply meditative and<br>relaxed state.<br>Himalayan River Stones &emsp;&emsp; 90 minutes<br>This ancient treatment uses smoothened river stones . Suffused with heat, these stones are placed along vital energy<br>points as your therapist provides you with thorough massage strokes, balancing the body&rsquo;s energy flow. The treatment<br>creates a synergy of warmth and powerful relaxation.</p>
    <img src = "obr5.png">
    <p style="text-align: center;margin-bottom: 0cm;background: transparent;line-height: 115%;">Facial Treatments<br>Soundarya Facial &ndash; For dry and mature skin &emsp;&emsp; 90 minutes<br>This exceptional facial helps to slow down the signs of premature aging,.Specialised lifting massage techniques combined<br>with the unique precious ingredients in this facial will help lift the skin and reduce signs of aging. Empowered with<br>rejuvenating properties of 24K Gold and the anti-oxidant properties of other precious minerals, this treatment begins<br>with a back massage and concludes with either a hand massage or a foot massage while the masque is on.<br>Tejas Jasmine &amp; Patchouli Facial &ndash; For oily skin&emsp;&emsp; 60 minutes<br>A corrective treatment customised to restore the balance of the skin. This purifying facial uses specific herbs, the floral<br>essence of pure jasmine, and tea tree and patchouli oils, renowned for their therapeutic qualities, to soothe the skin,<br>neutralise oil production and give an even skin tone. Skin impurities are gently removed, shine is reduced and pores are<br>tightened to leave your skin feeling clean, fresh and glowing with health.<br>Vedica Hydrating Facial &ndash; For dry and sensitive skin&emsp;&emsp; 60 minutes<br>Designed especially for sensitive skin, this calming and restorative skin treatment includes a combination of antioxidant<br>herbs and roots, and pure rose infusion to rebalance and restore your skin&rsquo;s vitality. It includes cleansing with traditional<br>Indian hand pounded Ubtans and fresh flower infused mists and lotions to create a hydrating facial experience.<br>Revitalising Men&rsquo;s Facial &ndash; All skin types&emsp;&emsp; 90 minutes<br>A deep skin cleansing and detox treatment, this purifying facial decongests the skin by unclogging blocked pores, rapidly<br>accelerating skin repair and neutralising impurities. Fast-acting and targeted botanical ingredients reduce sensitivity and<br>provide long-lasting defence against the damaging effects of daily pollutants, leaving the skin visibly clearer.<br>This treatment begins with a relaxing back massage and includes a choice of either a foot or hand massage while the<br>masque is on.</p>
    <img src = "obr6.png">
    <p style="text-align: center;margin-bottom: 0cm;background: transparent;line-height: 115%;">Yoga Stretch &amp; Daily Reflections<br>These include postures and breathing techniques that will help you attain a state of wellbeing and serenity.<br>Please press the &lsquo;Spa&rsquo; button on your guest room phone for a personalised yoga session.<br>For the Complete Spa Experience<br>To ensure your spa experience is relaxing we recommend the following:<br>&bull; To help you fully relax, The Oberoi Spa is a mobile and WiFi free zone.<br>&bull; Out of respect to all guests, we look to start and end your treatment on time.<br>&bull; Gentlemen who are having a facial are advised to shave at least 3 hours prior.<br>&bull; &nbsp; &nbsp;Guests with medical conditions and ladies who are pregnant should consult their doctor before scheduling<br>an appointment.<br>&bull; The spa is designed for guests 16 and above.<br>&bull; Please leave all jewellery behind when visiting the spa.<br>&bull; Spa robes &amp; slippers are available at the spa.<br>Reservations and Cancellations<br>All spa therapies can be scheduled or cancelled at the spa. We understand that unavoidable circumstances<br>may arise and cancelling your appointment might be necessary. If you find yourself unable to keep your<br>appointment, please contact the spa at least 4 hours in advance to avoid incurring the full charge of<br>your service.</p>
</div></div>