<div class = "flex flex-col items-center mt-10">
<div class = "">
    <p style="text-align: center;margin-bottom: 0cm;background: transparent;line-height: 115%;"><strong><span style="color: rgb(0, 0, 0);">SHOPPING IN UDAIPUR</span></strong></p>
<p style="text-align: center;margin-bottom: 0cm;background: transparent;line-height: 115%;"><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span style="color: rgb(0, 0, 0);"><strong>Udaipur, the erstwhile capital of the Mewar region of Rajasthan has a proud heritage as a center for crafts and performing arts.</strong></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><span style="color: rgb(0, 0, 0);">Udaipur is famous for its school of miniature paintings in the Rajput - Mughal style. These paintings, meticulous in detailing and delicate in brushwork, are done on cloth, marble, wood or paper. Meenakari, beautifully crafted enamel work is also indigenous to Udaipur. The Meenakari filigree animals and birds are richly coloured in enamel work of ruby reds, blues, greens and whites.&nbsp;</span></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><span style="color: rgb(0, 0, 0);">Bandhini &amp; Lehariya, age old techniques of tying and dyeing fabrics, are another specialty of the region. Traditional silver jewellery and silver artifacts are also available in the jewellery shops and throughout the markets of the old town.&nbsp;</span></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><span style="color: rgb(0, 0, 0);">The Oberoi Udaivil&atilde;s Front Desk team will be happy to make arrangements for you to visit the shops in the city. We would however, be unable to take responsibility for the quality and price of any items purchased outside of the hotel.&nbsp;</span></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><span style="color: rgb(0, 0, 0);"><span size="2" style="font-size:15px;"><u><strong>Tijori Boutique</strong></u></span></span><span style="color: rgb(0, 0, 0);"><span size="2" style="font-size:15px;"><strong>&nbsp;</strong></span></span><span style="color: rgb(0, 0, 0);">- The Oberoi, Udaivilas gift shop, &lsquo;Tijori&rsquo; is located just outside the main lobby area and offers an interesting selection of jewellery, handicrafts, textiles and clothing.&nbsp;</span></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span style="color: rgb(0, 0, 0);">&nbsp;</span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: center;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><strong>Enjoy your shopping excursions into Udaipur, where treasures are sure to be found!</strong></span></p>
<p style='text-align: center;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: center;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: center;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><strong>All shops mentioned above are subject to closure without prior notice on Public holidays, festivals and the decision of shop owners.</strong></span></p>
<p style='text-align: center;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><strong>For any further assistance please feel free to get it touch with our concierge.</strong></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<h2 style='text-align: center;margin-top: 0cm;background: transparent;text-decoration: underline;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;margin-bottom: 0.49cm;'><span style="color: rgb(0, 0, 0);"><span style="text-decoration: none;">ANTIQUES</span></span></h2>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><span size="2" style="font-size:13px;"><span style="color: rgb(0, 0, 0);"><strong>Name of the Shop: RAMA ARTS&nbsp;</strong></span></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><span size="2" style="font-size:13px;"><strong>Address: 1, Moti Magri Scheme, Udaipur 313001</strong></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><span size="2" style="font-size:13px;"><span style="color: rgb(0, 0, 0);"><strong>Owner: Mr. Hemant Periwal&nbsp;</strong></span></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><span size="2" style="font-size:13px;"><strong>Contact No.: Mr. Jayesh - 09829202551</strong></span></p>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><span style="color: rgb(0, 0, 0);"><span size="2" style="font-size:15px;"><strong>Email&nbsp;</strong></span></span><span style="color: rgb(0, 0, 0);"><span size="2" style="font-size:15px;">&nbsp;:&nbsp;</span></span><span size="2" style="font-size:15px;"><strong>periwalexports@rediffmail.com&nbsp;</strong></span><span style="color: rgb(0, 0, 0);"><span size="2" style="font-size:15px;"><u><strong>,</strong></u></span></span><span style="color: rgb(0, 0, 0);"><span size="2" style="font-size:15px;"><strong>&nbsp;mayurart@datainfosys.net</strong></span></span><span style="color: rgb(0, 0, 0);"><u>&nbsp;</u></span></span></p>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><strong>Timings: 10:00am to 07:00pm</strong></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;">Mayur Arts, which started in a small shop in the Lake Palace Hotel in 1984, moved out to a bigger place because of the expansion in the product range and increasing level of demand of artifacts which reflect true culture of Mewar and Rajasthan. Today Mayur Arts in its present form can boast to have the largest collection of old miniature paintings, marble &amp; brass artifacts, wooden furniture and artifacts, sandalwood</span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><span style="color: rgb(0, 0, 0);">carvings done by master craftsmen of national level, old doors, windows, ceiling, marble inlay table tops, old pichwais, swords, daggers with intricate work, silver articles and furniture.&nbsp;</span></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><span style="color: rgb(0, 0, 0);">&nbsp;</span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><span size="2" style="font-size:13px;"><strong>Name of the shop : NATIONAL ARTS &amp; HANDICRAFTS</strong></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><span size="2" style="font-size:13px;"><strong>Address :Near Backside of Mangalam Arts</strong></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><span size="2" style="font-size:13px;"><strong>Owner : Mr. Gopal Chauhan</strong></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><span size="2" style="font-size:13px;"><strong>Contact No. : 09414162589</strong></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><span size="2" style="font-size:13px;"><strong>Email : <a href="http://in.mc376.mail.yahoo.com/mc/compose?to=sales@nationalartsexpo.com" target="_blank">sales@nationalartsexpo.com</a></strong></span></p>
<h1 style='text-align: justify;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><br></h1>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><span style="color: rgb(0, 0, 0);"><span size="2" style="font-size:15px;"><strong>Timings: 07:00am to 05:00pm(Open on all Days)&nbsp;</strong></span></span><span style="color: rgb(0, 0, 0);"><strong>&nbsp;</strong></span></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><span style="color: rgb(0, 0, 0);"><span size="2" style="font-size:15px;">It is an</span></span><span style="color: rgb(0, 0, 0);">&nbsp;art school with a team of talented artist inheriting the patronage of art from their forefathers who worked as artist</span><span style="color: rgb(0, 0, 0);"><strong>s</strong></span><span style="color: rgb(0, 0, 0);">&nbsp;for the royal family of Mewar.&nbsp;</span></span></p>
<h1 style='text-align: justify;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><br></h1>
<h1 style='text-align: justify;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">Name of the shop: MANGALAM ARTS</span></h1>
<h1 style='text-align: justify;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">Address: Opp. Hero Honda Sukhadia Circle</span></h1>
<h1 style='text-align: justify;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">Contact No. : 0294-2425157 /58/59 , 09829643103&nbsp;</span></h1>
<h1 style='text-align: justify;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">Email: udaipur@mangalam.com</span></h1>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><strong>Contact Person: Mr. Shyam Rawat &ndash; 09829043406</strong></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><span style="color: rgb(0, 0, 0);"><span size="2" style="font-size:15px;"><strong>Timings: 09:30 am to 06:30 pm (Open on all Days except Sundays)&nbsp;</strong></span></span><span style="color: rgb(0, 0, 0);"><strong>&nbsp;</strong></span></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><span style="color: rgb(0, 0, 0);"><span size="2" style="font-size:15px;">A large warehouse style shop mainly offering reproductions, some handicrafts and a few antiques. The main branch of Mangalam Arts is located in Jaipur city</span></span><span style="color: rgb(0, 0, 0);">.&nbsp;</span></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: center;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: center;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><strong>TRADITIONAL CLOTHING</strong></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><strong>Name of the shop: SOMA (LADIES WEAR ONLY)</strong></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><strong>Address: Besides Hotel Mahendra Prakash,</strong></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;margin-left: 3.81cm;'><span style="color: rgb(0, 0, 0);">&nbsp;<strong>Boheda Ki Bari, Opposite Gulab Bagh</strong></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;margin-left: 2.54cm;text-indent: 1.27cm;'><span style="color: rgb(0, 0, 0);">&nbsp;<strong>Lake Palace Road, 313 &ndash; 001</strong></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><strong>Contact No.</strong><strong>: 0294-2420 475 , 09928020169</strong></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><strong><span style="color: rgb(0, 0, 0);">Contact person: Ms. Anju Sharma&nbsp;</span></strong></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><span style="color: rgb(0, 0, 0);"><span size="2" style="font-size:15px;"><strong>Timings: 10:00 am to 07:00 pm (Open on all Days)&nbsp;</strong></span></span><span style="color: rgb(0, 0, 0);"><span size="2" style="font-size:15px;"><strong>&nbsp;</strong></span></span><span style="color: rgb(0, 0, 0);"><strong>&nbsp;</strong></span></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><span style="color: rgb(0, 0, 0);">India is a country with a glorious tradition of fine textiles - silks, embroidery, mirror-work and block - prints prized for centuries around the world. For generations families in the villages state of Rajasthan&nbsp;</span></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;">have been producing exquisite block-printed textiles. Since 1984, Soma has been bringing these fine products to thousands of its consumers with consistent quality and world-class creativity.</span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><strong>Name of the shop: SADHNA&nbsp;</strong><strong>(LADIES WEAR ONLY)</strong></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><strong>Address: Old Fatehpura, Udaipur-313004, Rajasthan, India</strong></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><strong><span style="color: rgb(0, 0, 0);">Telephone no: 0294-2454655&nbsp;</span></strong></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><strong>Fax: 0294-2450947</strong></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><strong>E-mail : sadhna@sadhna.org</strong><span style="font-weight: normal;">,&nbsp;</span><u><a href="mailto:sadhna@sevamandir.org"><strong>sadhna@sevamandir.org</strong></a></u></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><strong><span style="color: rgb(0, 0, 0);">Contact Person : Ms. Madhu Detha (09414092949)&nbsp;</span></strong></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><strong>Timings: 10:00am to 06:00pm</strong></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><span style="color: rgb(0, 0, 0);">Sadhna is a Women&rsquo;s Handicraft Enterprise, specializes in accessories garments, home furnishings and Jewellery, which is anklets, bangles, earrings and necklace.&nbsp;</span></span></p>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><br></p>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><br></p>
<p style='text-align: center;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><strong>Name of the shop: THE RAYMOND SHOP</strong></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><strong>Address: 57/2A Sukhadia Circle, New Fatehpura</strong></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><strong>Telephone no.: 0294-252 8775</strong></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><span style="color: rgb(0, 0, 0);"><strong>Contact Person: Mr. Umesh&nbsp;</strong></span></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><span style="color: rgb(0, 0, 0);"><span size="2" style="font-size:15px;"><strong>Timings:10: 30 am to 08:30 pm (Open on all days and Sunday till 05pm)</strong></span></span><span style="color: rgb(0, 0, 0);"><strong>&nbsp;</strong></span><span style="color: rgb(0, 0, 0);"><strong>&nbsp;</strong></span></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><span style="color: rgb(0, 0, 0);">A store for men&rsquo;s clothing predominantly and offers a range of western clothing, including Levi&rsquo;s, as well as an extensive range of domestic and imported men&rsquo;s casual and dress shirts. Traditional formal Indian men&rsquo;s wear is a specialty of this shop. The store also offers a range of Samsonite suitcases.&nbsp;</span></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<h1 style='text-align: center;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: normal;line-height: 115%;'><br></h1>
<h1 style='text-align: center;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">JEWELLERY</span></h1>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><span style="color: rgb(0, 0, 0);"><strong>Name of the shop: SILVER ART PALACE&nbsp;</strong></span></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><strong>Address: 8, New Fateh Pura, Opp. Sahelio Ki Bari, Main Gate</strong></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><strong>Telephone no.: 09414163573</strong></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><strong>E mail: <a href="mailto:silverartpalace@rediffmail.com">silverartpalace@rediffmail.com</a></strong></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><strong>Contact Person</strong><strong>:</strong><strong>&nbsp;Mr. Sunil Chowdhary (09414168313)</strong></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><span style="color: rgb(0, 0, 0);"><span size="2" style="font-size:15px;"><strong>Timings: 10:00 am to 8 00 pm (Open on all Days)&nbsp;</strong></span></span><span style="color: rgb(0, 0, 0);"><strong>&nbsp;</strong></span></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;">The shop has a range of old silver &amp; gold, precious and semi precious stone jewellery, Indian &amp; Rajasthani traditional art can also be framed with beautiful stones and gems.</span></p>
<h1 style='text-align: justify;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><br></h1>
<h1 style='text-align: justify;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">Name of the shop: GEM ARTS EMPORIUM&nbsp;</span></h1>
<h1 style='text-align: justify;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">Address: 119 Saheli Marg Opp</span><span style="color: rgb(0, 0, 0);">.&nbsp;</span><span style="color: rgb(0, 0, 0);">Sahelion ki Bari&nbsp;</span></h1>
<h1 style='text-align: justify;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">Telephone no. : 0294-252 9020</span></h1>
<h1 style='text-align: justify;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">E-mail: gem_arts@hotmail.com</span></h1>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><strong>Contact Person: Mr. Sunil Dhaddha (0091- 9829040220)</strong></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><span style="color: rgb(0, 0, 0);"><span size="2" style="font-size:15px;"><strong>Timings: 9 30 am to 7 30 pm (Open on all Days)&nbsp;</strong></span></span><span style="color: rgb(0, 0, 0);"><strong>&nbsp;</strong></span></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><span style="color: rgb(0, 0, 0);">One of the oldest family run jewellery stores in Udaipur. A large collection of jewellery set with precious or semi precious gems in both modern settings and the traditional Moghul style settings. Silver ornaments&nbsp;</span></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><span style="color: rgb(0, 0, 0);">and giftwares, traditional tribal jewellery and an array of modern silver jewellery is also available in this very comfortable three room gallery. Gem Arts is located in the new city of Udaipur and easily accessible from The Oberoi, Udaivil&atilde;s. Request to meet with the owners, Sunil is extremely professional and very helpful as well as a pleasure to deal with. Gem Arts is a welcoming and comfortable shop to spend time in.&nbsp;</span></span></p>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><br></p>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><br></p>
<h1 style='text-align: justify;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">Name of the shop: ALANKAR JEWELLERS&nbsp;</span></h1>
<h1 style='text-align: justify;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">Address:&nbsp;</span><span style="color: rgb(34, 34, 34);">8, Hajareshwar Colony, Court Circle, Hospital Road, Udaipur</span></h1>
<h1 style='text-align: justify;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">Telephone no.: 0294 2525387, 0294-2421942</span></h1>
<h1 style='text-align: justify;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">E-mail: <a href="mailto:alankar_jewellers@yahoo.co.in">alankar_jewellers@yahoo.co.in</a></span></h1>
<h1 style='text-align: justify;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">Contact Person: Mr. Divya Makhija (</span>09829220221)</h1>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><span style="color: rgb(0, 0, 0);"><span size="2" style="font-size:15px;"><strong>Timings: 11:00 am to 08:00 pm (Sunday- 11am to 5pm)&nbsp;</strong></span></span><span style="color: rgb(0, 0, 0);"><strong>&nbsp;</strong></span><span style="color: rgb(0, 0, 0);"><strong>&nbsp;</strong></span></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;">One of the leading jewellery houses in Udaipur dealing in a variety of jewels. Its inception dates back to 1959. Blending the art of Rajasthan with modern day trends and fashion they have provided their customers with the most exclusive and reliable jewellers. The store is located in the old city of Udaipur and includes gold and silver ornaments, Diamond jewellery, and precious and semi precious stones.</span></p>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><br></p>
<h1 style='text-align: justify;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><br></h1>
<h1 style='text-align: justify;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">Name of the shop: TBZ &ndash; THE ORIGINAL</span></h1>
<h1 style='text-align: justify;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">Address: Near Sukhadiya Circle, Next to Royal Motor Company, Panchavati&nbsp;</span></h1>
<h1 style='text-align: justify;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">Telephone no.: 0294-2423002 / 2425001</span></h1>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><span size="2" style="font-size:13px;"><strong>Mobile : 08769262535</strong></span></p>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><span size="2" style="font-size:13px;"><strong>Website : www.tbztheoriginal.com</strong></span></p>
<h1 style='text-align: justify;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">Contact Person: Mr. Dhupia&ndash; Store Manager</span></h1>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><span style="color: rgb(0, 0, 0);"><strong>Timings: 11:00 am to 8:00 pm (Open all days)&nbsp;</strong></span><span style="color: rgb(0, 0, 0);"><strong>&nbsp;</strong></span></span></p>
<p style='text-align: justify;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;margin-top: 0.49cm;margin-bottom: 0.49cm;'><span size="2" style="font-size:13px;"><span style="background: #ffffff;">TBZ &ndash;&nbsp;</span>The Original, has a rich legacy of over 150 years. Our design sensibilities revolve around high quality, timeless, diamond and gold jewellery designed for customers who value beautiful creations. Our jewellery reflects many facets of the customer&rsquo;s personalities and encompasses a wide range including design styles that reflect the cultural heritage of Rajasthan. With a retail footprint of 31 stores nationally, we invite you to come experience an environment of sophistication and comfort where we promise to cater to your every need in a relaxed and personalized setting<span style="background: #ffffff;">.</span></span></p>
<h1 style='text-align: justify;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">Name of the shop: RAJASTHAN GEMS</span></h1>
<h1 style='text-align: justify;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">Address: Ground Floor Akruti Complex, Opp. Sahelion Ki Bari, New Fatehpura.</span></h1>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><span size="2" style="font-size:13px;"><span size="2" style="font-size:15px;"><strong>Mobile :</strong></span><span style="color: rgb(0, 0, 0);">&nbsp;</span><span style="color: rgb(0, 0, 0);"><strong>09414164064, 09928488844,&nbsp;</strong></span></span></p>
<h1 style='text-align: justify;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">E-mail</span><span style="color: rgb(0, 0, 0);">: info@rajasthangems.com</span></h1>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><span size="2" style="font-size:13px;"><strong>Website : www.rajasthangems.com</strong></span></p>
<h1 style='text-align: justify;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">Contact Person: Manoj Gandhi</span></h1>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><span style="color: rgb(0, 0, 0);"><strong>Timings: 11:00 am to 7:00 pm (Open all days)&nbsp;</strong></span><span style="color: rgb(0, 0, 0);"><strong>&nbsp;</strong></span></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><span style="color: rgb(0, 0, 0);">One of Udaipur&rsquo;s oldest family run jewelry stores with a large collection of gems &ndash; precious and semi precious, traditional Indian style old jewelry and Moghul style jewelry as well as a variety of Tibetann beads and silver tribal jewelry. A lovely selection of silver daggers and swords, both new and antique is also available as well as miniature paintings.&nbsp;</span><span style="color: rgb(0, 0, 0);"><strong>&nbsp;</strong></span><span style="color: rgb(0, 0, 0);"><strong>&nbsp;</strong></span></span></p>
<h1 style='text-align: justify;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><br></h1>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><br></p>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><br></p>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><br></p>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><br></p>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><br></p>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><br></p>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><br></p>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><br></p>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><br></p>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><br></p>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><br></p>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><br></p>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><br></p>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><br></p>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><br></p>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><br></p>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><br></p>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><br></p>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><br></p>
<h3 style='color: rgb(79, 129, 189);text-align: center;margin-top: 0.35cm;margin-bottom: 0cm;background: transparent;font-family: "Cambria", serif;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">PAINTINGS, TEXTILES &amp; HANDICRAFTS</span></h3>
<h3 style='color: rgb(79, 129, 189);text-align: justify;margin-top: 0.35cm;margin-bottom: 0cm;background: transparent;font-family: "Cambria", serif;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">Name of the shop: MEWAR ART GALLERY&nbsp;</span><span style="color: rgb(0, 0, 0);"><span style="font-weight: normal;">(</span></span><span style="color: rgb(0, 0, 0);">NEW CITY)</span></h3>
<h1 style='text-align: justify;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">Address: 10-A Sahelion Ki Bari, New Fatehpura&nbsp;</span></h1>
<h1 style='text-align: justify;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">E-mail : mewararts@hotmail.com</span></h1>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><strong>Contact Person: Mr. Love Gehlot 09828471091, 09829242274</strong></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><span style="color: rgb(0, 0, 0);"><span size="2" style="font-size:15px;"><strong>Timings: 10 00 am to 7 00 pm (Open on all Days)&nbsp;</strong></span></span><span style="color: rgb(0, 0, 0);"><strong>&nbsp;On Sundays: 10 00 am to 6 00 pm&nbsp;</strong></span></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><span style="color: rgb(0, 0, 0);">A collection of miniature paintings on cloth, wood, marble and paper. Ranging from small gift items in front room of the Gallery. The more valuable works of art are available to be viewed on request.&nbsp;</span></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><span style="color: rgb(0, 0, 0);">lower price ranges to more collectible pieces. Painting demonstrations take place in the&nbsp;</span></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<h3 style='color: rgb(79, 129, 189);text-align: justify;margin-top: 0.35cm;margin-bottom: 0cm;background: transparent;font-family: "Cambria", serif;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">Name of the shop: SHYAM ARTS</span></h3>
<h1 style='text-align: justify;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">Address: 2, &ldquo;Shatdal &ldquo;sahelion ki bari Udaipur &ndash; 313 001</span></h1>
<h1 style='text-align: justify;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">Telephone no.: 0294-2423751</span></h1>
<h1 style='text-align: justify;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">E-mail : shyamarts99@gmail.com</span></h1>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><strong>Contact Person : Hemendra Pujari (09414163256)</strong></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><span style="color: rgb(0, 0, 0);"><strong>Timings: 09 30 am to 7 30 pm (Open on all Days)&nbsp;</strong></span></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;">A collection of uinque miniature paintings on cloth, wood, marble and paper. Marble gifts, marble crafts, marble paintings, marble handicraft paintings, indian marble handicraft speciality in Pichhavais Paintings.</span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<h3 style='color: rgb(79, 129, 189);text-align: justify;margin-top: 0.35cm;margin-bottom: 0cm;background: transparent;font-family: "Cambria", serif;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);"><span size="2" style="font-size:15px;">Name of the shop: OM ARTS &amp; CRAFTS&nbsp;</span></span><span style="color: rgb(0, 0, 0);"><span size="2" style="font-size:15px;"><span style="font-weight: normal;">(</span></span></span><span style="color: rgb(0, 0, 0);">NEW CITY)</span></h3>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><span style="color: rgb(0, 0, 0);"><strong>Address: 45 New Fatehpura, Near Sukhadia Circle&nbsp;</strong></span></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><strong>Mobile: 09828144808, 09829043488</strong></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><strong>E mail:&nbsp;</strong><u><a href="mailto:omarts@indiatimes.com"><strong>omarts@indiatimes.com</strong></a></u></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><span style="color: rgb(0, 0, 0);"><strong>Contact Person: Mr. Kuldeep (09828144808)&nbsp;</strong></span></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><span style="color: rgb(0, 0, 0);"><span size="2" style="font-size:15px;"><strong>Timings: 10:00 am to 07:00 pm (Open on all Days)&nbsp;</strong></span></span><span style="color: rgb(0, 0, 0);"><strong>&nbsp;</strong></span></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;">A collector&rsquo;s paradise located in the heart of new city and has a collection of miniature paintings, pichwaies done by renowned artists, range of antiques reproduction, sandalwood carvings, artists are working onsite to demonstrate traditional miniature painting techniques.</span></p>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><br></p>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><br></p>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><br></p>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><br></p>
<h3 style='color: rgb(79, 129, 189);text-align: justify;margin-top: 0.35cm;margin-bottom: 0cm;background: transparent;font-family: "Cambria", serif;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">Name of the shop: ROYAL ARTS &amp; CRAFTS (NEW CITY)</span></h3>
<h1 style='text-align: justify;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">Address: 42 Dewali, Near Fateh Sagar Lake&nbsp;</span></h1>
<h1 style='text-align: justify;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">Telephone no. : 0294-2451054&nbsp;</span></h1>
<h1 style='text-align: justify;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">Fax no. : 0294-2453957</span></h1>
<h1 style='text-align: justify;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">Email : <a href="mailto:info@royalartsandcraftsudaipur.com">info@royalartsandcraftsudaipur.com</a></span></h1>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><strong>Contact person: Mr. G Singh &amp; Mr. M Mehta</strong></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;margin-left: 3.81cm;'><span size="2" style="font-size:13px;"><span style="color: rgb(0, 0, 0);"><strong>: Mr. Sunder Lal (09460085155)&nbsp;</strong></span></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><span style="color: rgb(0, 0, 0);"><span size="2" style="font-size:15px;"><strong>T</strong></span></span><span style="color: rgb(0, 0, 0);"><span size="2" style="font-size:15px;"><strong>imings: 9 30 am to 8 00 pm (Open on all Days)&nbsp;</strong></span></span><span style="color: rgb(0, 0, 0);"><strong>&nbsp;</strong></span></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span style="color: rgb(0, 0, 0);">&nbsp;</span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><span style="color: rgb(0, 0, 0);">A one stop store spread in 25000sq. feet area abounds one&rsquo;s imagination for the search of traditional exclusive items of interest from handicrafts to textiles. Handicrafts items of brass, silver, bone and&nbsp;</span></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><span style="color: rgb(0, 0, 0);">wooden artifacts. Authentic collection of miniature paintings by national award winning artists, depicting the glorious India.&nbsp;</span></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<h3 style='color: rgb(79, 129, 189);text-align: justify;margin-top: 0.35cm;margin-bottom: 0cm;background: transparent;font-family: "Cambria", serif;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">Name of the shop: BRAHMA ARTS &amp; TEXTILES</span></h3>
<h1 style='text-align: justify;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">Address: Lake Palace Road, Udaipur</span></h1>
<h1 style='text-align: justify;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">Telephone no. : 09829044114&nbsp;</span></h1>
<h1 style='text-align: justify;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">Email :&nbsp;</span>brahmaudaipur@gmail.com</h1>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><strong>Contact person: Mr. Mahendra Vikram Singh</strong></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><span style="color: rgb(0, 0, 0);"><span size="2" style="font-size:15px;"><strong>T</strong></span></span><span style="color: rgb(0, 0, 0);"><span size="2" style="font-size:15px;"><strong>imings: 10 00 am to 8 00 pm (Open on all Days)&nbsp;</strong></span></span><span style="color: rgb(0, 0, 0);"><strong>&nbsp;</strong></span></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span style="color: rgb(0, 0, 0);">&nbsp;</span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;">A unique collection of Miniature paintings, Old (Antiques) miniature paintings and Pichwais done by National awarded artists. In Handicraft large collection of Marble, Brass, Artifacts, Wooden Furniture, Old doors, windows &amp; artifacts.</span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><br></p>
<h1 style='text-align: justify;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">Name of the shop: RAMA KRISHNA</span></h1>
<h1 style='text-align: left;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">Address: 8, New Fateh Pura, Opp. Sahelio Ki Bari, Main Gate</span></h1>
<h1 style='text-align: left;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">Telephone no.: 09414163573</span></h1>
<h1 style='text-align: left;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">E-mail:&nbsp;</span><span style="color: rgb(0, 0, 255);"><u><a href="mailto:ramakrishnatextiles@gmail.com">ramakrishnatextiles@gmail.com</a></u></span></h1>
<h1 style='text-align: left;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">Contact Person: Mr. Babu Lal Soni (09983343573)</span></h1>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><span style="color: rgb(0, 0, 0);"><span size="2" style="font-size:15px;"><strong>Timings: 10 00 am to 8 00 pm (Open on all days)</strong></span></span><span style="color: rgb(0, 0, 0);"><strong>&nbsp;</strong></span><span style="color: rgb(0, 0, 0);"><strong>&nbsp;</strong></span></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><span style="color: rgb(0, 0, 0);">It has a unique collection of textile, pashmina shawls, old and new embroidery and Jari work. Ready to wear dress material, made to measure clothing&rsquo;s. A resident tailor is on hand for custom made clothes of excellent fit and quality at very short notice.&nbsp;</span></span></p>
<p style="text-align: left;margin-bottom: 0cm;background: transparent;"><br></p>
<p style="text-align: left;margin-bottom: 0cm;background: transparent;"><br></p>
<p style="text-align: left;margin-bottom: 0cm;background: transparent;"><br></p>
<p style="text-align: left;margin-bottom: 0cm;background: transparent;"><span size="2" style="font-size:13px;"><strong>PICHHAVAIS PAINTING</strong></span></p>
<h1 style='text-align: justify;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">&nbsp;</span></h1>
<h1 style='text-align: justify;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">Name of the shop: SHREENATH SILVER &amp; ART&nbsp;</span></h1>
<h1 style='text-align: justify;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">Address: City Palace Rd. Udaipur&nbsp;</span></h1>
<h1 style='text-align: justify;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">Telephone no.: 0294-242 2803</span></h1>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><strong>Contact Person: Mr. Vinay Gurani (09928087290)</strong></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><span style="color: rgb(0, 0, 0);"><span size="2" style="font-size:15px;"><strong>Timings: 10:00 am to 07:00 pm (Open on all Days)&nbsp;</strong></span></span><span style="color: rgb(0, 0, 0);"><strong>&nbsp;</strong></span></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;">It showcases the world famous Pichhavais Painting and is located outside the main gate of the city palace.</span></p>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><br></p>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><br></p>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><span size="2" style="font-size:13px;"><strong>Name of the shop: RIVAYAT PASHMINA</strong></span></p>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><span size="2" style="font-size:13px;"><span size="2" style="font-size:15px;"><strong>Address: 12-A, alkapuri, 2kms from the Oberoi Udaivilas.&nbsp;</strong></span></span></p>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><span size="2" style="font-size:13px;"><strong>Telephone no. : +91 9818080646</strong></span></p>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><span size="2" style="font-size:13px;"><strong>Contact person: Mr. Muz Affar, Mr. Feroz (Store Manager) 8233818063</strong></span></p>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><span size="2" style="font-size:13px;"><strong>Social media handle (Instagram ): @rivayatpashmina</strong></span></p>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><br></p>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><span size="2" style="font-size:13px;"><strong>Timings: 10AM TO 7PM (Open all days )</strong></span></p>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><br></p>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><span size="2" style="font-size:13px;"><span size="2" style="font-size:15px;">Shop that specializes in fine quality merchandise of cashmere ( Pashmina ), value for money with the great ambience and quality &amp; variety to offer.&nbsp;</span></span></p>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><br></p>
<p style='text-align: center;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: center;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><strong>INDIAN TEXTILES AND CLOTHING</strong></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><span style="color: rgb(0, 0, 0);"><strong>Name of the shop: MAHARANI EMPORIUM&nbsp;</strong></span></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><span style="color: rgb(0, 0, 0);"><strong>Address: 113, Opposite Sahelion ki Bari&nbsp;</strong></span></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><span style="color: rgb(0, 0, 0);"><strong>Telephone no.: 0294-2415760&nbsp;</strong></span></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><strong>Contact Person: Mr. Chandresh Shrimali (+91 9799104647, 9829044992)</strong></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><strong>E-mail : maharaniudp@yahoo.co.in</strong></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><span style="color: rgb(0, 0, 0);"><span size="2" style="font-size:15px;"><strong>Timings: 11:00 am to 07:00 pm (Open on all Days)&nbsp;</strong></span></span><span style="color: rgb(0, 0, 0);"><strong>&nbsp;</strong></span></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><span style="color: rgb(0, 0, 0);">It has a unique collection of textile, pashmina shawls, old and new embroidery. Ready to wear dress material, made to measure clothing&rsquo;s. A resident tailor is on hand for custom made clothes of excellent fit and quality at very short notice.&nbsp;</span></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><strong>Name of the shop: MADHUSHREE SAREES</strong></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><span style="color: rgb(0, 0, 0);"><strong>Address: 2-C, Panchwati circle, Udaipur&nbsp;</strong></span></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><strong>Telephone no: 0294-2418708</strong></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><span style="color: rgb(0, 0, 0);"><strong>Mob : 09784590750&nbsp;</strong></span></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><strong>E-mail: madhushreeudr@gmail.com</strong></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><strong>Contact Person: Mr. Ravi Parikh</strong></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;">The store is exclusively for bridal and designer fashion store in bridal lehengas, designer sarees, fancy badhni, sarees, lehengas and leharias.</span></p>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><br></p>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><br></p>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><br></p>
<h1 style='text-align: justify;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">Name of the shop: GANESH HANDICRAFT EMPORIUM &ndash; CITY PALACE ROAD</span></h1>
<h1 style='text-align: justify;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">Telephone no.: 0294-2523647</span></h1>
<h1 style='text-align: justify;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">E-mail : ganesh_emporium@yahoo.com</span></h1>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><span style="color: rgb(0, 0, 0);"><span size="2" style="font-size:15px;"><strong>Contact Person: Mr. Laxman Jain (09462192255)&nbsp;</strong></span></span><span style="color: rgb(0, 0, 0);"><span size="2" style="font-size:15px;"><strong>Timings: 9 00 am to 08 00 pm (Open on all Days)&nbsp;</strong></span></span><span style="color: rgb(0, 0, 0);"><strong>&nbsp;</strong></span></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><span style="color: rgb(0, 0, 0);">A large store front and two floors of textiles mark the entrance down the winding little back alley to the back rooms of the Ganesh Emporium, located on the same street as Jagdish Temple. A three level shop offering an array of embroidery work, wall hangings, bags, cushion covers &amp; bed covers, silks, pashmina wraps and many more exquisite items.&nbsp;</span></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><br></p>
<h1 style='text-align: justify;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">Name of the shop: ANOKHI&nbsp;</span></h1>
<h1 style='text-align: justify;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">Address: City Palace Complex, Manek Chowk</span></h1>
<h1 style='text-align: justify;margin-top: 0cm;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;font-weight: bold;line-height: 115%;'><span style="color: rgb(0, 0, 0);">Telephone no.: 0294-2529881&nbsp;</span></h1>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;"><strong>Timing: 9 30 am to 5 30 pm (Open on all days)</strong></span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><br></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;'><span size="2" style="font-size:13px;">One of a chain of shops throughout India, offering 100% cotton clothing &ndash; men&rsquo;s, women&rsquo;s and children&rsquo;s, plus a variety of home wares, the majority of which are done with block print patterns. Clean, modern and very comfortable with knowledgeable and pleasant staff.</span></p>
<p style='text-align: justify;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;line-height: 115%;margin-left: 3.81cm;text-indent: -3.81cm;'><br></p>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><br></p>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><br></p>
<h3 style='color: #4f81bd;text-align: left;margin-top: 0.35cm;margin-bottom: 0cm;background: transparent;font-family: "Cambria", serif;font-weight: bold;line-height: 115%;'><br></h3>
<p style='text-align: left;margin-bottom: 0cm;background: transparent;font-family: "Times New Roman", serif;font-size:15px;'><br></p>
</div>
</div>